# This is a basic workflow to help you get started with Actions

name: RP2-CI-CD

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

  workflow_dispatch:

jobs:
  build_jar:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
            distribution: "temurin"
            java-version: "8"
            cache: "gradle"
      - name: Run build
        run: ./gradlew build
      - uses: benjlevesque/short-sha@v2.2
        id: ssha
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/libs/*
          file_glob: true
          tag: ${{ github.ref }}-${{ steps.ssha.outputs.sha }}
          overwrite: true
          body: "Automatic build message"