# This is a basic workflow to help you get started with Actions

name: RP2-CI-CD

on:
  push:
    branches: [ "build" ]
  pull_request:
    branches: [ "build" ]

  workflow_dispatch:

jobs:
  build_jar:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '8'
            cache: 'gradle'

      - name: Run build
        run: ./gradlew build

      # - name: Upload jars
        # uses: actions/upload-artifact@v3
        # with:
          # path: ./build/libs/
      - name: Upload binaries to release
        uses: benjlevesque/short-sha@v2.2
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/libs/*
          file_glob: true
          tag: ${{ github.ref }}-${{ env.sha }}
          overwrite: true
          body: "Automatic build message"